# Generated by Django 5.2.3 on 2025-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_new_options_comment_sub_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
