# Generated by Django 5.2.3 on 2025-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('tries', models.SmallIntegerField(default=0)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('extra_fields', models.JSONField(default=dict)),
                ('next_step', models.CharField(choices=[('step2', 'step2'), ('regis', 'regis'), ('login', 'login')], default='step2')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
